/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

/**
 *
 * @author USUARIO
 */
public class FrmMain extends javax.swing.JFrame {
    FrmProducto producto;
    FrmConsProd consprod;
    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        
        producto =  new FrmProducto();
        consprod = new FrmConsProd();
        this.jDesktopPane1.add(producto);
        this.jDesktopPane1.add(consprod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MI_Salir = new javax.swing.JMenuItem();
        Menu_Prod = new javax.swing.JMenu();
        MI_Ingresar = new javax.swing.JMenuItem();
        MI_consultar = new javax.swing.JMenuItem();
        MI_Actualizar = new javax.swing.JMenuItem();
        Menu_Empleado = new javax.swing.JMenu();
        MI_ingresar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(221, 40));

        jMenu1.setText("File");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        MI_Salir.setText("Salir");
        MI_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MI_SalirMouseClicked(evt);
            }
        });
        MI_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_SalirActionPerformed(evt);
            }
        });
        jMenu1.add(MI_Salir);

        jMenuBar1.add(jMenu1);

        Menu_Prod.setText("Producto");
        Menu_Prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ProdActionPerformed(evt);
            }
        });

        MI_Ingresar.setText("Ingresar");
        MI_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_IngresarActionPerformed(evt);
            }
        });
        Menu_Prod.add(MI_Ingresar);

        MI_consultar.setText("Consultar");
        MI_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_consultarActionPerformed(evt);
            }
        });
        Menu_Prod.add(MI_consultar);

        MI_Actualizar.setText("Actualizar");
        Menu_Prod.add(MI_Actualizar);

        jMenuBar1.add(Menu_Prod);

        Menu_Empleado.setText("Empleado");

        MI_ingresar.setText("Ingresar");
        Menu_Empleado.add(MI_ingresar);

        jMenuItem2.setText("Consultar");
        Menu_Empleado.add(jMenuItem2);

        jMenuBar1.add(Menu_Empleado);

        jMenu4.setText("Cliente");

        jMenuItem3.setText("Ingresar");
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Consultar");
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Proveedor");

        jMenuItem5.setText("Ingresar");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Consultar");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Pedidos");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MI_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_IngresarActionPerformed
        // TODO add your handling code here:
        
        producto.show();
    }//GEN-LAST:event_MI_IngresarActionPerformed

    private void Menu_ProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ProdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Menu_ProdActionPerformed

    private void MI_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MI_SalirMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MI_SalirMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1MouseClicked

    private void MI_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_consultarActionPerformed
        // TODO add your handling code here:
        consprod.show();
    }//GEN-LAST:event_MI_consultarActionPerformed

    private void MI_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MI_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MI_Actualizar;
    private javax.swing.JMenuItem MI_Ingresar;
    private javax.swing.JMenuItem MI_Salir;
    private javax.swing.JMenuItem MI_consultar;
    private javax.swing.JMenuItem MI_ingresar;
    private javax.swing.JMenu Menu_Empleado;
    private javax.swing.JMenu Menu_Prod;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
